### ISSUE TITLE
CSS-in-JS with SSR

### ISSUE THREAD

**Issue by mufasa71** [vikejs/vike-vue#141]
Unable to extract CSS and put it into <head /> tag. For example:

```ts
import { createSSRApp } from 'vue'
import { renderToString } from '@vue/server-renderer'
import { setup } = from '@css-render/vue3-ssr'

// For each request, you need to create a new app
const ssrApp = createSSRApp(App)
const { collect } = setup(ssrApp)

renderToString(ssrApp).then(appHtml => {
  const css = collect()
  const page = `<!DOCTYPE html>
  <html>
    <head>${css}</head>
    <body><div id="app">${appHtml}</div></body>
  </html>`
})
```

as you see here we can extract CSS and render as part of HTML template.

I didn't found a way how to do it properly. Probably a new functionality should be added

**Comment by brillout** [comment]
It's indeed a current limitation.

The plan is to eventually have this:

```js
// /pages/+onBeforeRenderHtml.js

import { setup } from '@css-render/vue3-ssr'

export default pageContext => {
  pageContext.collect = setup(pageContext.app)
}
```
```js
// /pages/+onAfterRenderHtml.js

import { useConfig } from 'vike-vue/useConfig'

export default pageContext => {
  const config = useConfig()
  const css = pageContext.collect()
  config({ head: { dangerouslyInject: css } })
}
```

It's considered `highest-priority` so you can expect it to land sooner rather than later.

**Comment by pool611** [comment]
when I use vike-react, there is no onAfterRenderHtml hook😥

**Comment by brillout** [comment]
@pool611 FYI creating these hooks is the easy part. The tricky part is `useConfig()` (there is already a rough implement but it needs polishing). I'll tentatively try to get something released this week.

**Comment by brillout** [comment]
The `useConfig()` hook is done for React: https://github.com/vikejs/vike-react/pull/128 which I'll merge after I finish writing the docs for it. Porting it to `vike-vue` should be relatively straightforward.

**Comment by brillout** [comment]
Done.

https://vike.dev/onBeforeRenderHtml
https://vike.dev/onAfterRenderHtml
https://vike.dev/useConfig

Pre-released as `0.8.1-commit-4184bec`.

**Comment by brillout** [comment]
Definitely let us know if you hit any issues about the head management improvements. We're looking for feedback; there is room for improvement which we will be implementing upon user feedback.

**Comment by lewis-fidlers** [comment]
Hi, i know it's not exactly the correct spot to post this question, but this seems like exactly what I'm trying to do. Pretty new to the whole ssr thing. 

We currently have vike setup with vike-react. And are using ant.design for our ui stuff. (we're moving from a very old stack to vike)

As per their guide, i should be able to extract the css and inject it into the page. https://ant-design.github.io/antd-style/guide/ssr 

Similar to what you wrote above the hooks are however not available in vike-react, just vike-vue if I'm correct? Is there another approach needed? Or am i missing something here?

Cheers, Lewis

**Comment by mufasa71** [comment]
@brillout unfortunately its not working as expected.

1. [onBeforeRenderHtml](https://vike.dev/onBeforeRenderHtml) has no vue app instance, its impossible to collect styles
2. [onAfterRenderHtml](https://vike.dev/onAfterRenderHtml) impossible to call `useConfig` `setPageContext() not called`

seems like its not simple changes, but i think app should be created on very first step and passed to down to context, then we can use `onBeforeRenderHtml` only and it should solve the issue

**Comment by brillout** [comment]
@mufasa71 That should be fixable. Let me circle back on this at the beginning of next week.

**Comment by lewis-fidlers** [comment]
@pool611 I believe this might be of help to you as well: https://github.com/vikejs/vike/discussions/1804

**Comment by brillout** [comment]
@mufasa71 Can you publish it on Github?

**Comment by Jearce** [comment]
@brillout I have a minimal working example here: https://github.com/Jearce/vike-vue-naive-ui. Seems fine to me.

**Comment by pdanpdan** [comment]
Check the example just above

**Comment by phonzammi** [comment]
@Jearce, I'm sorry, but I think there’s a typo: `config({ head:` should be `config({ Head:` with a capital H.

**Comment by Jearce** [comment]
Thanks, I see what you mean. The example I shared above is a false positive even fixing the typo. I was able to confirm with the following command:
`curl -s http://localhost:3000/ | awk '/<\<head>/,/<\/head>/ {print}'`

The head HTML, server-side, is not being rendered with the CSS. I think the [getHeadHtml](https://github.com/vikejs/vike-vue/blob/9ed291f7b5929acd44f3d3e853a977384fd8aa8e/packages/vike-vue/src/renderer/onRenderHtml.ts#L85) function would need to be updated to consider injecting raw CSS/style string in head.

**Comment by Jearce** [comment]
@phonzammi This seemed to work: ` config({ Head: css })`

**Comment by brillout** [comment]
> I think the [getHeadHtml](https://github.com/vikejs/vike-vue/blob/9ed291f7b5929acd44f3d3e853a977384fd8aa8e/packages/vike-vue/src/renderer/onRenderHtml.ts#L85) function would need to be updated to consider injecting raw CSS/style string in head.


I think doing something similar to what we're doing in the example below works?

```js
config({
  Head: h('script', {
    type: 'application/ld+json',
    innerHTML: JSON.stringify({
      '@context': 'https://schema.org/',
      contentUrl: { src },
      creator: {
        '@type': 'Person',
        name: author,
      },
    }),
  }),
})
```

**Comment by Jearce** [comment]
Yes, that works:
```
 config({ 
    Head: h('style', {
      innerHTML: css
    })
  })
```
I updated the example I shared above and the styles are now correctly rendered server-side.

**Comment by brillout** [comment]
@Jearce Thank you! I've added your example to the docs https://vike.dev/naive-ui. Also, a Vike extension `vike-vue-naive-ui` would be neat in case that's something you'd be up for. You can have a look at https://github.com/vikejs/vike-vue/tree/main/packages/vike-vue-pinia and https://github.com/vikejs/vike-vue/tree/main/packages/vike-vue-query &mdash; it's relatively simple.

@mufasa71 If you're up for it, you can publish a working example, and I'll link to it from the docs.

I guess we can close this. Let us know if you run into any unresolved issues.

**Comment by phonzammi** [comment]
> ```js
>  config({ 
>     Head: h('style', {
>       innerHTML: css
>     })
>   })
> ```

I'm sorry, but I don’t think it’ll work. The `css` already includes multiple `<style>` tags, and when I tried it, I saw a FOUC for a second. But we can use a custom `tag` like this :
```js
config({
    Head: h("css-style", {
      innerHTML: css,
    }),
  });
```

**Comment by brillout** [comment]
@phonzammi :+1: Or using a fragment instead of `css-style` would work as well I guess. I can't speak for Jearce but I guess PR welcome to https://github.com/Jearce/vike-vue-naive-ui.

**Comment by brillout** [comment]
Improved the docs https://vike.dev/Head and added [How to injecting raw HTML?](https://vike.dev/Head#how-to-injecting-raw-html).

**Comment by Jearce** [comment]
@phonzammi Thanks! The issue should be fixed now. 
@brillout Yes, I am down. I'll make a PR for the Vike extension when ready.

**Comment by brillout** [comment]
Neat :100:. If you want, we can host the extension under your name at https://github.com/Jearce/vike-vue-naive-ui (I guess we can move the example to another URL like https://github.com/Jearce/vike-naive-ui). I went ahead and grabbed https://www.npmjs.com/package/vike-vue-naive-ui &mdash; let me know what your npm handle and I'll make you co-admin.

**Comment by Jearce** [comment]
@brillout My npm handle is jearce and https://github.com/Jearce/vike-vue-naive-ui should be a valid vike extension now. I will add an example later this week.

**Comment by brillout** [comment]
Awesome :100: Updated docs: https://vike.dev/naive-ui. (As for the exmple `@todo` I recommend a pnpm monorepo with at the root: `example/` and `packages/vike-vue-naive-ui/` or `vike-vue-naive-ui/`.)

**Comment by mufasa71** [comment]
@brillout @Jearce  just checked and everything works fine now. Great Job! Looking forward to the naive extension, so far the package seems broken :)

**Comment by Jearce** [comment]
@brillout Done. The git repo is now a pnpm monorepo and should be ready to publish to npm. I don't have perm to publish myself. The package should work although I only tested it on a local Verdaccio instance.

**Comment by brillout** [comment]
@Jearce :100: Let me know your npm handle and I'll make you co-admin.

**Comment by Jearce** [comment]
npm handle: https://www.npmjs.com/~jearce

**Comment by brillout** [comment]
Done.
```bash
$ npm owner add jearce vike-vue-naive-ui
+ jearce (vike-vue-naive-ui)
```
