### ISSUE TITLE
How to use vue plugin

### ISSUE THREAD

**Issue by Jimmyzm** [vikejs/vike-vue#16]
I just read the doc and code that found there is no way to install and use the vue plugin with this adapter. Could you please tell me how to do or add a way to do that?

**Comment by AurelienLourot** [comment]
Hey @Jimmyzm, thanks for reaching out. The easiest way to get started is to either copy an [example](https://github.com/vikejs/vike-vue/tree/main/examples/basic) or to scaffold a new project using https://batijs.github.io/

Here you can see how the examples glue together Vike (vite-plugin-ssr) with vitejs/plugin-vue: https://github.com/vikejs/vike-vue/blob/main/examples/basic/vite.config.ts

Here is where vike-vue gets plugged into Vike: https://github.com/vikejs/vike-vue/blob/main/examples/basic/pages/%2Bconfig.h.ts#L17

Let me know if anything is unclear. Recently we decided to reduce the readmes to a bare minimum and have them point at https://vite-plugin-ssr.com/ but thanks to this issue and after a conversation with @brillout, we now think the readmes of vike-vue, [vike-react](https://github.com/vikejs/vike-react) and [vike-solid](https://github.com/magne4000/vike-solid) should be more elaborated. I'll keep this issue open and work on that (FYI @magne4000)

**Comment by Jimmyzm** [comment]
@AurelienLourot , thanks for the reply, what I mean is not about the vitejs/plugin-vue, it's about the plugins made for the vue ecosystem, the usage is [here](https://vuejs.org/api/application.html#app-use), they need the app instance to take effect before mounted.

**Comment by AurelienLourot** [comment]
Ah right, that's not possible yet. I didn't think of it, thanks a lot. I'll add a config option for that.

**Comment by AurelienLourot** [comment]
@Jimmyzm I have now implemented a `vuePlugins` option that takes a list of plugins with their respective options.

> [!NOTE]
> It plays nicely with the `ssr` option: if you want SSR it will install the plugin both on the server and on the client. If you don't want SSR it will load it only on the client.

I have created an example on how to install a plugin: https://github.com/vikejs/vike-vue/blob/main/examples/with-vue-plugin/pages/%2BvuePlugins.ts

I still need to:

* [ ] Release a new `vike-vue` version so you can make use of that
* [ ] Properly document all this
* [ ] Improve the example to install a real plugin instead of a dummy one

Let me know if there is anything else

**Comment by Jimmyzm** [comment]
@AurelienLourot thanks a lot! I just found if I import plugins at the `+config.h.ts` file with the `vuePlugins` option, It does not work at all because of the doc I found. [Not re-exported imports](https://vite-plugin-ssr.com/header-file#not-re-exported-imports)

**Comment by AurelienLourot** [comment]
Indeed it's easier to create a `+vuePlugins.ts` file than to extend `+config.h.ts`. Vike will simply detect `+vuePlugins.ts` and use its return value as `vuePlugins` config option. This is true for any `+<something>.ts` file, by the way, except the special `+config.h.ts` file.
