### ISSUE TITLE
Vue Devtools-Next errors when trying to evaluate pageContext 

### ISSUE THREAD

**Issue by pdanpdan** [vikejs/vike-vue#160]
I'm not sure if this should be solved in `vike` or in `devtools-next` (https://github.com/vuejs/devtools-next) or in both.

When inspecting components that use `usePageContext` in `script setup` devtools will try to check some marker/well-known keys for internal purposes in `prepare.js`.

```js
let n = G(()=>St(t.setupState[o])), r = e[o], s, a = typeof n == "function" || typeof (n == null ? void 0 : n.render) == "function" || typeof (n == null ? void 0 : n.__asyncLoader) == "function" || typeof n == "object" && n && ("setup"in n || "props"in n) || /^v[A-Z]/.test(o);
```

This will produce calls to `getPageContextProxyForUser` for key `render` at least, and that will produce an `[vike][Wrong Usage] pageContext.render isn't defined on the client-side` error.

It looks like normal (non-next) vue devtools works.

@brillout Maybe this should be forwarded to the vue devtools team, but I think you can decide better.

**Comment by brillout** [comment]
Thank you for raising the issue. The [`getPageContextProxyForUser.ts` file](https://github.com/vikejs/vike/blob/ea4f7a97ee419cf7187c7f86359d9d146811c4a9/vike/client/shared/getPageContextProxyForUser.ts) already has a couple of Vue-specific whitelisting logic. How about we whitelist `render`? Would that be enough?

If `assertUsage()` causes too many issues, then let's make it a `assertWarning()` instead.

**Comment by pdanpdan** [comment]
Maybe the whitelisting should be established together with the devtools team, so that is they check for something new they should notify in the vike repo.

**Comment by brillout** [comment]
I agree, although I ain't sure how much interest they'll show in maintaining such list :thinking: Maybe it's worth a try.

**Comment by pdanpdan** [comment]
I'll make a simple repo showing the problem and open an issue on their repo referencing this issue.

**Comment by brillout** [comment]
👍

**Comment by brillout** [comment]
@martijndirksen Yea, let's give whitelisting a last chance and if we can't make it work then let's make it a warning. (Thanks for sponsonring btw! :green_heart:)

**Comment by pdanpdan** [comment]
@brillout Can you please take over the technical part here?
https://github.com/vuejs/devtools-next/issues/542#issuecomment-2249207276

**Comment by brillout** [comment]
@pdanpdan Done :+1:

**Comment by pdanpdan** [comment]
Fixed in devtools

**Comment by brillout** [comment]
Neat, thank you for reaching out @pdanpdan

**Comment by brillout** [comment]
> I would prefer a warning instead of assertUsage as well.

This is the plan so far: https://github.com/vikejs/vike/issues/1776.
