### ISSUE TITLE
New components `<Head>` and `<Config>`

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-vue#175]
The PR https://github.com/vikejs/vike-vue/pull/170 introduced the [`useConfig()` component hook](https://vike.dev/useConfig) to `vike-vue`, see [this usage example](https://github.com/vikejs/vike-vue/blob/c1f988837f8b90ebe2e43b258137916e30b8f7be/examples/full/pages/images/Image.vue#L15-L32).

The only thing missing to align with `vike-react` is to implement [the `<Config>` and `<Head>` components](https://vike.dev/useConfig#config-head).

My failed attempt to implement it: https://github.com/vikejs/vike-vue/pull/174.

I wonder: does Nuxt have something like [Next.js's `<Head>` component](https://nextjs.org/docs/pages/api-reference/components/head)?

Contribution welcome.

**Comment by pdanpdan** [comment]
It looks like at least `Head` key in config only allows 1 element, not a list (https://github.com/vikejs/vike-vue/blob/b65d7866736bf52249a5fd6918b65de2ef4db6db/packages/vike-vue/src/hooks/useConfig/useConfig-server.ts#L48)
I'm not sure if it works in `vike-react` (maybe it's wrapped in a fragment?)

**Comment by brillout** [comment]
@pdanpdan Thanks for reviewing this.

> It looks like at least `Head` key in config only allows 1 element, not a list

I've doubled checked quickly and it does seem like `pageContext._configFromHook.Head` is treated as an array throughout the code.

> And I just want to check: on client side `['Head', 'description', 'image']` should be ignored

Agreed and IIRC it's already the case.

**Comment by phonzammi** [comment]
@pdanpdan, what do you think of this https://github.com/vikejs/vike-vue/pull/176/commits/74aeb17bafdacba8bc9d76a92491e4753de681e2?

**Comment by pdanpdan** [comment]
I made the required changes in https://github.com/vikejs/vike-vue/pull/174/

**Config**: I don't know how to make a Head attr work in config (and I don't think is very Vue-ish), so Config works as Head - the default slot is used for tags to be rendered in head.
**Head**: It should be emphasized in the docs that:
- it only works on server side (on client side it is NOOP)
- it is strictly additive (every time a <Head> is encountered it will add its content to <head>, even if the same content already exists)
- what is generated by Head on server side is never removed on client-side navigation
- it should not be used with any tag that is already processed by something else (title, description, any meta generated from title and description, ...)

**Comment by pdanpdan** [comment]
I updated https://github.com/vikejs/vike-vue/pull/174 and all works as expected now.

**Comment by pdanpdan** [comment]
Looking at what can be done with `Config` and `Head`, don't you think it would be enough to have the `Config` one but named `Head`?

**Comment by brillout** [comment]
> It should be emphasized in the docs that:
> 
> * it only works on server side (on client side it is NOOP)
> * it is strictly additive (every time a  is encountered it will add its content to , even if the same content already exists)
> * what is generated by Head on server side is never removed on client-side navigation
> * it should not be used with any tag that is already processed by something else (title, description, any meta generated from title and description, ...)

I think it's already the case?
- https://vike.dev/Head#only-html
- https://vike.dev/Head#cumulative

**Comment by brillout** [comment]
> Looking at what can be done with `Config` and `Head`, don't you think it would be enough to have the `Config` one but named `Head`?

Yea, I though a lot about it. The thing is that `useConfig()`/`<Config>` are also meant for non-head things such as `bodyAttributes` (and potentially more even more unrelated configs) which is one reason why I ended up with that naming.

All-in-all, I ended up liking https://vike.dev/useConfig#config-head but let me know if you see DX issues with it.

**Comment by pdanpdan** [comment]
What I implemented in https://github.com/vikejs/vike-vue/pull/174 is:
- Head - working as in the docs
- Component - working as in the docs with added that default slot children work as in `Head` and have precedence over Head attr/prop

`Head` is a little redundant (it's `Config` but without other props than Head).

I have improved them over what is in the PR with props (instead of attrs) to improve editor DX, but it's not pushed yet - I was waiting for your opinion about a few things:
- props vs attrs (see this comment https://github.com/vikejs/vike-vue/pull/176#issuecomment-2286340972)
- should we only define as props `title` in Config-client? I think the editor will use the definition in `Config-server` anyway
- should we improve what is updated client-side? I would suggest 'favicon', 'lang', 'bodyAttributes', 'htmlAttributes' (this is also related to your question here: https://github.com/vikejs/vike-vue/issues/183#issue-2468009347)

**Comment by brillout** [comment]
> * working as in the docs with added that default slot children work as in `Head`

I share the sentiment that it saves the user from having to use both `<Config>` and `<Head>` at the same time, but I'm a little bit reluctant because it makes explaining things in the docs a bit harder (it's a slightly non-intuitive/non-trivial API), and it's slighlty less future proof.

Functionnally, I agree that `<Head>` and `<Config>` are redundant, but I like it because it's more readable. I think this:

```jsx
<Config title={data.title} />
<Head>
  <meta property="og:image" content={data.previewImage} />
</Head>
<ul>{
  data.movies.map(({ title }) => (
    <li>{title}</li>
  ))
}</ul>
```

is clearer than that:

```jsx
<Config title={data.title}>
  <meta property="og:image" content={data.previewImage} />
</Config>
<ul>{
  data.movies.map(({ title }) => (
    <li>{title}</li>
  ))
}</ul>
```


> * props vs attrs (see this comment [feat: new components `<Head>` and `<Config>` #176 (comment)](https://github.com/vikejs/vike-vue/pull/176#issuecomment-2286340972))

How about we define the props while doing the following to avoid code duplication:

```diff
- export type ConfigFromHook = PickWithoutGetter<
-   Vike.Config,
-   'Head' | 'title' | 'description' | 'image' | 'favicon' | 'lang' | 'viewport' | 'bodyAttributes' | 'htmlAttributes'
- >
+ const configsFromHook = ['Head', 'title', 'description', 'image', 'favicon', 'lang', 'viewport', 'bodyAttributes', 'htmlAttributes'] as const
+ type ConfigsFromHook = (typeof configsFromHook)[number]
+ export type ConfigFromHook = PickWithoutGetter<
+   Vike.Config,
+   ConfigsFromHook
+ >
```

I think that would be the perfect solution then?

Btw. [we added `watchEffect()` to `useConfig()`](https://github.com/vikejs/vike-vue/commit/846c4cd1723890dabc44d6372d2403c35a07a731).

(FYI I'll improve the `configFromHook` naming once the head management improvements start to stabilize.)

> * should we only define as props `title` in Config-client? I think the editor will use the definition in `Config-server` anyway

:+1:

> * should we improve what is updated client-side? I would suggest 'favicon', 'lang', 'bodyAttributes', 'htmlAttributes' (this is also related to your question here: [`vike-vue-unhead` #183 (comment)](https://github.com/vikejs/vike-vue/issues/183#issue-2468009347))

:+1: I agree for lang; [I went ahead and implement it](https://github.com/vikejs/vike-vue/commit/ff901d887fc905081856474131a12f05d7735197).

The `bodyAttributes` and `htmlAttributes` settings [are global](https://vike.dev/bodyAttributes#global) for now, so we don't need to update them. Let's see if users need `{body,html}Attributes` to be non-global (I do expect so, but I wanted to prioritize other things before working on this).

I purposely decided to remove support for [non-global favicons](https://vike.dev/favicon#global) because it's a very seldom use case and [users can implement it themselves](https://vike.dev/head-tags#custom-settings). Note that a non-global favicon setting wouldn't help implementing dynamic icons like GMail and Discord (I do consider these use cases to be somewhat common but the users have to implement them themselves in the user-land; I don't think Vike can/should help).

**Comment by pdanpdan** [comment]
Updated implementation in https://github.com/vikejs/vike-vue/pull/174:
- `Config` no longer use default slot for Head tags
- `Config` uses props instead of attrs

It should be ready, if you want some changes please tell me.

**Comment by brillout** [comment]
Nice :eyes: I'll have a look.
