### ISSUE TITLE
_headAlreadySet does not work as expected on client side

### ISSUE THREAD

**Issue by pdanpdan** [vikejs/vike-vue#181]
`_headAlreadySet` has the same problem as `_configFromHook`.

I made a simple repro for the problem in https://github.com/vikejs/vike-vue/pull/179

- in `useConfig` (in useConfig-client) the check is against `_headAlreadySet` from reactive pageContext
- in `_headAlreadySet` (in onRenderClient) pageContext is not created reactive with a `_headAlreadySet` key

What I can see is:

- setting title on server side works as expected
- setting title on client side on navigation works as expected
- setting title on client side after navigation is done (eg. in a setTimeout) does not work

Rest of comments are here: https://github.com/vikejs/vike-vue/pull/178#issuecomment-2286282274

**Comment by brillout** [comment]
:+1: Fixed.
