### ISSUE TITLE
Cumulative settings in config(htmlAttributes|bodyAttributes) should merge what is set in +config with what is set using useConfig?

### ISSUE THREAD

**Issue by pdanpdan** [vikejs/vike-vue#182]
Now if we defined `bodyAttributes: { class: 'dark' }` in `+config`
and defined `bodyAttributer: { 'data-test': 'test' }` using `useConfig`
only the value from `_configFromHook` will be used.

Is this what is expected?

And if they are cumulative maybe content merge should be implemented at least for `class`.

**Comment by brillout** [comment]
:+1: Indeed `getHeadSettings()` should cumulate the values instead of overwriting.

**Comment by pdanpdan** [comment]
What about `class`?

**Comment by brillout** [comment]
> What about `class`?

https://github.com/vikejs/vike-vue/issues/175#issuecomment-2293516677
