### ISSUE TITLE
The execution order of `applyHeadSettings()` (formerly `updateDocument()`) and the `useConfig()` hook

### ISSUE THREAD

**Issue by phonzammi** [vikejs/vike-vue#184]
Comparison with `vike-react`:

* `vike-react`: Call `updateDocument()` first, followed by the `useConfig()` hook during page navigation.
* `vike-vue`: Call the `useConfig()` hook first, followed by `updateDocument()` (renamed `applyHeadSettings()`) during page navigation.

Since `pageContext.isHydration` is `false` during page navigation (after the first render), then this :

https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/renderer/onRenderClient.ts#L20

will return `pageContext._headAlreadySetWrapper = { val: false }`

Consequently, `useConfig()` hook will get `pageContext._headAlreadySetWrapper = { val: false }` and never call `apply()` function.

~~One solution I can tell is to place `applyHeadSettings()` twice, after [`app.mount()`](https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/renderer/onRenderClient.ts#L34) and before [`await changePage(pageContext)`](https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/renderer/onRenderClient.ts#L39).~~

~~Edit: A better solution I've tried is to place `applyHeadSettings()` twice :~~
~~1. After [`app.mount()`](https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/renderer/onRenderClient.ts#L34), and~~

We only need to call `applyHeadSettings()` after [`onChangePage?.(pageContext)`](https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/renderer/createVueApp.ts#L87)

With the above solution, we don’t need the workaround involving `_headAlreadySetWrapper?: { val: boolean }`. We can use the previous method with `_headAlreadySet?: true` instead.

**Comment by phonzammi** [comment]
I made a simple repro here #185.
How to reproduce: 
* Checkout to #185 branch
* Run `pnpm install && pnpm build`
* `cd examples/full/ && pnpm dev`
* Open `http://localhost:3000/` on the browser and also open the browser devtool
* Click on `Route Function` link to navigate and look at the console to see the execution order

**Comment by brillout** [comment]
> Comparison with `vike-react`:
> 
> * `vike-react`: Call `updateDocument()` first, followed by the `useConfig()` hook during page navigation.
> * `vike-vue`: Call the `useConfig()` hook first, followed by `updateDocument()` (renamed `applyHeadSettings()`) during page navigation.

Seems like an issue on vike-react's side: the rendering of the page should awaited for before `applyHeadSettings()` is called.

**Comment by phonzammi** [comment]
It is, isn'it? It's called it if `!pageContext.isHydration`, when client side navigaition

**Comment by phonzammi** [comment]
A better solution I've tried is to place `applyHeadSettings()` twice : 
1. After [`app.mount()`](https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/renderer/onRenderClient.ts#L34), and
2. After [`onChangePage?.(pageContext)`](https://github.com/vikejs/vike-vue/blob/18cfd3baaf55f572057ca9ce1a6c26b0cc35940e/packages/vike-vue/src/renderer/createVueApp.ts#L87)

**Comment by brillout** [comment]
Closing as per https://github.com/vikejs/vike-vue/pull/185#issuecomment-2293907387.
