### ISSUE TITLE
`useConfig()` isn't called upon same-page navigation

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-vue#187]
See reprod https://github.com/vikejs/vike-vue/pull/186:

- Go to http://localhost:3000/.
- Click on "Route Function"  => title is "changed"
- Click on "Route Function" again => tilte is "My Vike + Vue App" which is wrong as it should be "changed"

The issue here is that the setup script of `hello/+Page.vue` isn't called upon same-page navigation.

@phonzammi @pdanpdan Ideas for how to fix this?

**Comment by phonzammi** [comment]
It's works using vue's `watchEffect()` :

```js
import { watchEffect } from 'vue'
import { useConfig } from 'vike-vue/useConfig'

const config = useConfig()

watchEffect(() => {
  config({
    title: 'changed',
  })
})
```

**Comment by phonzammi** [comment]
Using Vue's `watchEffect()` in the return of the client-side `useConfig()` hook works.
I’ve tried it, and it works with #185, but it doesn’t work with the latest code of `vike-vue`.

```js
// useConfig-client.ts
function useConfig(): (config: ConfigFromHook) => void {
  // Vike hook
  let pageContext = getPageContext() as PageContext & PageContextInternal
  if (pageContext) return (config: ConfigFromHook) => setPageContextConfigFromHook(config, pageContext)

  // Component
  pageContext = usePageContext()
  return (config: ConfigFromHook) => {
    watchEffect(() => {
      if (!pageContext._headAlreadySet) {
        setPageContextConfigFromHook(config, pageContext)
      } else {
        apply(config)
      }
    })
  }
}
```

Please try it and let me know what you think :pray:

**Comment by brillout** [comment]
Indeed, it fixes the issue :ok_hand:
