### ISSUE TITLE
Typo: Steam should be Stream :)

### ISSUE THREAD

**Issue by pdanpdan** [vikejs/vike-vue#191]
https://github.com/vikejs/vike-vue/blob/2222a097d70e5dc467e74a831cd4f81b4e175de8/packages/vike-vue/src/types/PageContext.ts#L29

I haven't check in other places, on my mobile today.

**Comment by brillout** [comment]
Good catch, thank you :ok_hand:

**Comment by brillout** [comment]
I just checked and it was the only place.
