### ISSUE TITLE
bug when disabling cumulative layouts

### ISSUE THREAD

**Issue by RGdevz** [vikejs/vike-vue#201]
I tried to change the layout cumulative option to false because I don't want nested layouts , I changed the +Config file like this

```typescript
  meta: {
   Layout: {
    env: { server: true, client: true },
    cumulative: false,
   },
```

but it's not affecting it

after testing I changed the `+Config.ts` file in the extension itself but it didn't exactly work because 
  in `/src/integration/createVueApp.ts` the `layoutRef` is doing `forEach` loop but when disabling the `cumulative` it's not an array but a object so its erroring

**Comment by brillout** [comment]
See https://github.com/vikejs/vike/issues/1692 and the workaround discussed there.
