### ISSUE TITLE
`<ClientOnly>` Component

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-vue#27]
Since `vike-react` now has a [`<ClientOnly>` component](https://github.com/vikejs/vike-react/pull/35), it would be great to align `vike-vue` to also have such component.

**Comment by royalswe** [comment]
I use Evan You's example from vitepress in my project

````
import { ref, onMounted, defineComponent } from 'vue'

export const ClientOnly = defineComponent({
  setup(_, { slots }) {
    const show = ref(false)
    onMounted(() => {
      show.value = true
    })
    return () => (show.value && slots.default ? slots.default() : null)
  }
})

**Comment by brillout** [comment]
@royalswe Thanks for sharing 💯 We'll be adding a `<ClientOnly>` component (although we'll probably go for a slightly different implemention that leverages a dynamic `import()` in order to load the wrapped component only on the client-side which is frequent need).

**Comment by AurelienLourot** [comment]
Thank you for the donation @royalswe :green_heart:
