### ISSUE TITLE
Register plugins that don't use `app.use`

### ISSUE THREAD

**Issue by 4350pChris** [vikejs/vike-vue#60]
Hey, I'm in the process of converting a project I'm working on to use this integration and replace my custom one.
However, one thing I don't know how to solve right now is registering client-side plugins that don't use `app.use` - specifically, the Sentry plugin.
Here's the code I'm currently using in my `+onRenderClient.ts` file (truncated):

```ts
import { init as sentryInit, BrowserTracing } from "@sentry/vue";
// ...
export async function onRenderClient(pageContext: PageContextClient) {
  if (!app) {
    // ...
    const { sentryRelease, sentryDsn } = pageContext;
    sentryInit({
      app,
      dsn: sentryDsn,
      integrations: (defaults) =>
        defaults.concat(
          new BrowserTracing({
            tracingOrigins: [/.*.example.com/, /^\//],
          })
        ),
      // Set tracesSampleRate to 1.0 to capture 100%
      // of transactions for performance monitoring.
      // We recommend adjusting this value in production
      tracesSampleRate: 0.2,
      logErrors: !import.meta.env.PROD,
      environment,
      release: sentryRelease,
    });
  // ...
  }
  // ...
}
```

Now, I could move this to the [client init code](https://vike.dev/migration/v1-design#client-init-code) or do it in my root component using `import.meta.env.SSR` - however, that would delay the plugin's registration and I'm worried some errors might not be propagated to Sentry in that case, which is why this is one of the first things I'm doing right now in the aforementioned file.

Any suggestions how I could leverage what's available right now to do this properly?

**Comment by brillout** [comment]
I can make `+client.js` to be the first lines of JavaScript that are injected, which would solve the issue right?

**Comment by 4350pChris** [comment]
I'm not sure. Imo the documentation on that is lacking - in what context is the script executed, e.g. do I have access to pageContext already? Just from looking at it, it looks like it is plain JS that gets injected, probably before the Vue app is initialized, which would mean I can't register sentry either (since it needs the Vue app). So Sentry really should be initialized after creating `app` but before rendering it - both of which happen in `onClientRender.ts` right now. I'm sure there's a way to do it if I *really* wanted to by queueing any errors and waiting for Sentry to be initialized, but I'd rather not add complexity around that.

**Comment by brillout** [comment]
I see. How about a custom hook `onCreateApp()` provided by `vike-vue`? (And, yes, better documentation is very much on the radar.)

**Comment by 4350pChris** [comment]
Yup, sounds like the best approach here.

**Comment by brillout** [comment]
PR welcome if you want :) (but let us know if you're busy, I can implement it).

**Comment by s-ol** [comment]
Hey, I'm trying to migrate an existing app to vike and I'm having trouble with vue-i18n. I've created a `+onCreateApp.ts` file in the root of the pages directory:


```
// https://vike.dev/onCreateApp
import type { OnCreateAppSync } from 'vike-vue';
import type { Component } from 'vue';
import { i18n } from '../i18n';
import '../css/index.scss';

export const onCreateApp: OnCreateAppSync = (pageContext): ReturnType<OnCreateAppSync> => {
  const { app } = pageContext;

  const components = import.meta.glob('./components/*.vue', { eager: true, import: 'default' })
  Object.entries(components).forEach(([path, definition]) => {
    const componentName = path.split('/').pop()!.replace(/\.\w+$/, '');
    app.component(componentName, definition as Component);
  });

  app.use(i18n);

  // for debugging only:
  (app.config as any).___TAINTED = true;
  console.log('!!!!! VUE USE i18n !!!!', pageContext.urlOriginal);
}
```

but using the `$t` global causes this error, as if the `app.use` call were ignored:

```
TypeError: _ctx.$t is not a function
    at dist/server/entries/src_pages_index.mjs:357:515
```

I've tried logging both the app from vike's pageContext as well as vue's getCurrentApp():

`pages/index/+Page.vue`:
```
import { getCurrentInstance } from "vue";
import { usePageContext } from 'vike-vue/usePageContext'
const {app,urlOriginal} = usePageContext();
console.log("!!!!! PAGE-VIKE", urlOriginal, (app as any).config.___TAINTED);
console.log("!!!!! PAGE-VUE", urlOriginal, (getCurrentInstance() as any)?.config?.___TAINTED);
```

which logs this:

```
!!!!! VUE USE i18n !!!! /
!!!!! PAGE-VIKE / true
!!!!! PAGE-VUE / undefined
```

so it seems that onCreateApp is called, but perhaps a different vue app instance is used when actually prerendering the site? If relevant, I'm using prerendering (`vike({ prerender: true })`).

**Comment by brillout** [comment]
@s-ol Create a new discussion at `vikejs/vike` with a minimal reproduction with that you expect and what happens instead.
