### ISSUE TITLE
Improve DX of ClientOnly component

### ISSUE THREAD

**Issue by 4350pChris** [vikejs/vike-vue#67]
It'd be nice if we could have proper completion when using `ClientOnly`.
E.g.

```vue
// Component.vue
<template>
  <p>{{ msg }}</p>
</template>
<script lang="ts" setup>
  defineProps<{ msg: string }>()
</script>

// App.vue
<template>
  <ClientOnly
    :load="() => import('./Component.vue')"
    msg="Hello World"
  />
</template>
```

Here we don't get a hint for `msg` even though it's passed to `Component.vue`.

**Comment by brillout** [comment]
An easy workaround would be that we write the `d.ts` ourselves, instead of using the generated one.

**Comment by 4350pChris** [comment]
> An easy workaround would be that we write the `d.ts` ourselves, instead of using the generated one.

Could you elaborate?

My thinking was doing something along these lines

`ClientOnly.vue`
```vue
<script lang="ts" setup generic="T">
  type Props = {
     load: T
  }

  type ForwardProps = Awaited<ReturnValue<T>>["props"] // this isn't correct, I don't know how to get the props of the loaded component as of now

  defineProps<Props & ForwardProps>()
</script>
```

**Comment by brillout** [comment]
I don't know much about Vue's TypeScript support but, in principle, if we manually create the `.d.ts` file for `ClientOnly` ourselfes then that should work (assuming SFC's TypeScript support is "lossless").

I guess the question boils down to that: can we make it work when the user doesn't use SFC? If yes and if SFC TypeScript is lossless, then we're good.
