### ISSUE TITLE
Client side routing with catch all page throwing error

### ISSUE THREAD

**Issue by mohammadsiddiqui** [vikejs/vike-vue#79]
I have a catch all route which works fine from SSR but when we navigate from one page to another on the client side, the navigation doesn't happen.

Repo to reproduce: https://github.com/mohammadsiddiqui/h3-vike
Steps to reproduce: 
 - Navigate to home page 
 - Click on the link Create (this will work)
 - Click on Update (this fails)

 Catch all on client seems to be working for the first route occurrence but second time it fails. 

This is the error i am getting
 
`chunk-CRYGExF-.js:13 Error: You stumbled upon a vike-vue bug. Go to https://github.com/vikejs/vike-vue/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at _l (chunk-CRYGExF-.js:17:5413)
    at ml (chunk-CRYGExF-.js:17:5691)
    at chunk-h72aJ6Vq.js:1:74
    at Dn.fn (chunk-CRYGExF-.js:9:8919)
    at Dn.run (chunk-CRYGExF-.js:9:1446)
    at get value (chunk-CRYGExF-.js:9:9163)
    at li (chunk-CRYGExF-.js:9:1618)
    at get dirty (chunk-CRYGExF-.js:9:1165)
    at I.l.update (chunk-CRYGExF-.js:13:27958)
    at Ue (chunk-CRYGExF-.js:13:46)`

**Comment by brillout** [comment]
Thank you for creating the bug report, I will have a look at it later today. (Apologies for the delay.)

**Comment by brillout** [comment]
It seems to be an issue on Vue's side, I'll resuming digging tomorrow.

**Comment by brillout** [comment]
Fix released in `0.6.3`.

**Comment by brillout** [comment]
Repro fixed: https://github.com/brillout/vike-vue-bug-79.
