### ISSUE TITLE
`clientOnly()` function instead of `<ClientOnly>` wrapper component

### ISSUE THREAD

**Issue by brillout** [vikejs/vike-vue#82]
See:
 - https://github.com/vikejs/vike-solid/pull/74
 - https://docs.solidjs.com/solid-start/reference/client/client-only

I think we can & should also deprecate the `<ClientOnly>` wrapper component in favor of a `clientOnly()` function. It's a much nicer DX.

**Comment by pdanpdan** [comment]
Hello.
Can you please take a look at https://github.com/vikejs/vike-vue/pull/110?
It's about this issue and https://github.com/vikejs/vike-vue/issues/67

It's not polished and there are decisions to be made about:
- should the component be removed
- the name of the function (maybe `createClientOnlyComponent`)
- where it is exposed
- the name of the fallback slot (maybe `ssr-content`)
- I need some help with a typing error when resolving import (https://github.com/vikejs/vike-vue/pull/110/files#diff-e0ffd04a4eabd913ea52d413b3cb2221e6b1ff796c6981a2adecf58a067031b3R79)

But at least it works with props, events, and slots

**Comment by brillout** [comment]
> * should the component be removed

Does `<ClientOnly>` support any use case that `clientOnly()` doesn't? If not then, yes, I think we should remove it and release a breaking change and bump the minor semver. We're still on `0.x.y` so I think it's ok.

> * the name of the function (maybe `createClientOnlyComponent`)

I think `clientOnly()` is both succint and clear?

> * where it is exposed

So far, we export utils at `vike-vue/utilName`. So `vike-vue/clientOnly`.

Eventually merging exports to the root export `vike-vue` is a consideration, but we need to double check whether Rollup's code-splitting works (it should in principle, but we should be sure about it as bloating the client-side is a no-go).

> * the name of the fallback slot (maybe `ssr-content`)

How about `<template #fallback>`?

> * I need some help with a typing error when resolving import (https://github.com/vikejs/vike-vue/pull/110/files#diff-e0ffd04a4eabd913ea52d413b3cb2221e6b1ff796c6981a2adecf58a067031b3R79)

I'll have a look at it later today.

**Comment by pdanpdan** [comment]
- I cannot think of anything that `<ClientOnly>` can do better that the function
- `clientOnly` does not convey that it creates a component (`defineComponent`, `defineAsyncComponent` - maybe `defineClientOnlyComponent`)
- `<template #fallback>` - I was thinking about avoiding as much as possible to override a named slot of the wrapped component

**Comment by brillout** [comment]
> * `clientOnly` does not convey that it creates a componen

Unless I'm missing something, I think it's ok.

> * `<template #fallback>` - I was thinking about avoiding as much as possible to override a named slot of the wrapped component

Good point. How about an option? For example:

```ts
function clientOnly(
  componentLoader: () => Component,
  { fallbackSlotName = 'fallback' }: { fallbackSlotName?: string } = {}
) {
  // ...
}
```

**Comment by brillout** [comment]
> * I need some help with a typing error when resolving import (https://github.com/vikejs/vike-vue/pull/110/files#diff-e0ffd04a4eabd913ea52d413b3cb2221e6b1ff796c6981a2adecf58a067031b3R79)

The generic can be any type, maybe we should make it more restrictive?

For example, TS won't complain with the following:

```ts
clientOnly(
  () => 12
)
```

Did you mean more something like `T extends { new (): ComponentPublicInstance }` instead of `T extends Component = { new (): ComponentPublicInstance }`?

**Comment by pdanpdan** [comment]
- if we allow changing the fallback slot name with parameter we lose the autocomplete
- I tested with using a Symbol for slot name - it works but autocomplete is not available and one need to import the symbol, so not very nice to use
- I went the route of using a descriptive name of 'client-only-fallback'

About typing, I cannot make heads or tails of why it accepts something like `() => 2`, so if someone can bring some sanity there while still keeping autocomplete on use please help.

**Comment by brillout** [comment]
@4350pChris WDYT? I'll have a look at it if Chris is busy.

**Comment by brillout** [comment]
I don't know much about Volar, but I presume using a generic to do the trick?

```ts
function clientOnly<Component, FallbackSlotName extends string = 'fallback'>(
  componentLoader: () => Component,
  { fallbackSlotName }: { fallbackSlotName?: FallbackSlotName } = {}
) {
  // ...
}
```

See for example the type of `slotName1` and `slotName2` in [this playground](https://www.typescriptlang.org/play/?#code/GYVwdgxgLglg9mABBANjApmKB5MKCeAPAGICGKKARqRANYDKKcUAcqQLbqLoAeUmAEwDOiIVABOMMAHNEAXkQByYOSo1aigHwAKAFCJEKitTqNmbTgH4AXIjLH1Z1h3S6AlLftrTTZ50QA3voG4uhQIOJIRt4MvhZcpCKkYPi6AL66EAhionEuAIzyyGiYOHj42m6Z2VC55i4ATEWoGFi4BNrKqia0ALQNim5AA).

**Comment by pdanpdan** [comment]
I cannot make it work, sorry

**Comment by pdanpdan** [comment]
For me the steps are:
- `pnpm reset`
- reload VSCode so that TS is loaded with new `vike-vue`
- it should work now

**Comment by brillout** [comment]
Ah, it works now! Thanks. Sorry I'm a VSCode newbie :sweat_smile:

**Comment by pdanpdan** [comment]
No problem - I feel the same with TS magic (especially when combined with Vue)

**Comment by pdanpdan** [comment]
It would be the same problem with TS - we cannot make the slot name dynamic and still expose it in typescript (at least I don;t know how)

**Comment by brillout** [comment]
It isn't dynamic and instead we define two static slots `fallback` and `client-only-fallback`.

**Comment by brillout** [comment]
> Maybe it's a bit tricky to implement?

If it's too tricky then I'd say let's go for only one slot `client-only-fallback`. But maybe it's worth trying? I think the docs can be clear:
 > Use `#client-only-fallback` if the inner component uses `#fallabck`.

**Comment by pdanpdan** [comment]
Ah, you mean like that (define both slots) - it might work. Meanwhile if someone can understand why `() => 1` satisfies `T extends Component` it would help :D

**Comment by brillout** [comment]
Looking at it as we speak :)

I think the issue is somewhere else: https://play.vuejs.org/#eNp9kE9PwzAMxb+Klcs2aRpCcJoGEqBJwAEQcMylytzSkTpR4oyiqt8dp9X+HIBb/H4v9rM7deP9YpdQLdUqmlB7hoicPNiCqiutOGp1raluvAsMHQQsDNc7nAN/e4Q7J4CQGHoog2tgIr0mmjSVicToCEqamuXROOt6gTQ9n2lanY0jZYAUjI23BaNU92ity/xEU3MJYxyVdbXYRkeSuNMEoJWR3rXF8OzzQAm8hIFkVkijr8dB45BwvtfNB5rPX/RtbLOm1UvAiGGHWh0YF6FCHvH67QlbeR9g4zbJivsf+IrR2ZQzjrbbRBuJfeIb0j4Mt66peo/rlpHifqkcNDv7wa+VnDqf9a/Vj3EvFpfDP0296n8AX0unrg==

Let me have a closer look.

**Comment by brillout** [comment]
Btw. I think you can remove `= { new (): ComponentPublicInstance }`, since `source` is a required parameter.

**Comment by brillout** [comment]
Actually, `() => 1` is a valid `Component`: https://play.vuejs.org/#eNp9kE9PwzAMxb+Klcs2aRpCcJq2SYAmAQdAwDGXKnNLR+pEiTOGqn53nFb7cwBu8fu92M9u1Y33s11CNVeLaELtGSJy8mALqpZacdRqpaluvAsMLQQsDNc7nAJ/e4Q7J4CQGDoog2tgJL1GmjSVicToCEoam/nJOGk7gTQeT2C5gsuJpsXFMFjGSMHYeFswSnWP1rrMzzQ1lUjGUVlXs210JLlbTQBaGZlQWwzPPo+V2HPoSWaFNPp67DUOCacH3Xyg+fxF38Z91rR6CRgx7FCrI+MiVMgDXr894V7eR9i4TbLi/ge+YnQ25YyD7TbRRmKf+fq0D/3Fa6re43rPSPGwVA6anV3v10oOno/71+qnuFez6/6fpk51P/UzqLo=

Which makes sense from a JSX perspective.

**Comment by pdanpdan** [comment]
> Btw. I think you can remove = { new (): ComponentPublicInstance }, since source is a required parameter.

For some reason if I remove that we lose autocomplete for props/events/slots for resulting component

> Actually, () => 1 is a valid Component

Nice - you're right

**Comment by brillout** [comment]
> For some reason if I remove that we lose autocomplete for props/events/slots for resulting component

Sounds like a Volar quirk.

**Comment by pdanpdan** [comment]
Yep, editor quirk.
I updated the PR - it has 2 commits - the second one should be removed before merge

**Comment by 4350pChris** [comment]
@pdanpdan Can I merge this? Looks good from my point of view.

**Comment by pdanpdan** [comment]
Yes, all done from my point of view

**Comment by pdanpdan** [comment]
BTW, do you have any idea about this?
https://github.com/vikejs/vike-vue/pull/110#discussion_r1630722333

**Comment by 4350pChris** [comment]
> BTW, do you have any idea about this?
> https://github.com/vikejs/vike-vue/pull/110#discussion_r1630722333

Unfortunately no. I tried a bit and couldn't get it working either.
